### ISSUE TITLE
[Bug] 路由器OpenClash TUN模式，手机通过AP访问m.baidu.com，一段时间后无法打开搜索结果的链接

### ISSUE THREAD

**Issue by ximiTech** [Dreamacro/clash#2255] opened 2022-08-07 00:45 UTC
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

2022.07.07

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
#===================== 系统信息 =====================#

主机型号: Default string Default string/SKYBAY - Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz : 2 Core 4 Thread
固件版本: OpenWrt SNAPSHOT r4755-d8e34160b
LuCI版本: git-22.211.60098-feaa27a-1
内核版本: 5.18.15
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 32144
运行权限: 32144: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2022.07.07-7-g56f0a92
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.11.4-6-gbec4df7
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: v1.12.0
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/config.yaml
启动配置文件: /etc/openclash/config.yaml
运行模式: redir-host-tun
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 启用
仅代理命中规则流量: 启用
仅允许常用端口流量: 启用
绕过中国大陆IP: 停用
DNS远程解析: 停用
路由本机代理: 停用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用
```

### Clash log

```shell
内核日志:
2022-08-07 08:20:20 level=info msg="[TCP] 10.10.10.242:54397 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:20 level=info msg="[TCP] 10.10.10.242:54396 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:20 level=info msg="[TCP] 10.10.10.242:54395 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:20 level=info msg="[TCP] 10.10.10.242:54394 --> wakeup.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:20 level=debug msg="[Process] find process wakeup.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:20 level=info msg="[TCP] 10.10.10.242:54393 --> boxer.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:20 level=debug msg="[Process] find process boxer.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:20 level=info msg="[TCP] 10.10.10.242:54392 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:20 level=info msg="[TCP] 10.10.10.242:54391 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:20 level=info msg="[TCP] 10.10.10.242:54390 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:20 level=info msg="[TCP] 10.10.10.242:54389 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:19 level=info msg="[TCP] 10.10.10.242:54388 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:19 level=info msg="[TCP] 10.10.10.242:54387 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:19 level=info msg="[TCP] 10.10.10.242:54386 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:19 level=info msg="[TCP] 10.10.10.242:54385 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:19 level=info msg="[TCP] 10.10.10.242:54384 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:19 level=info msg="[TCP] 10.10.10.242:54383 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54381 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54380 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54379 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54378 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54377 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54376 --> fclick.baidu.com:443 match DomainSuffix(fclick.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54375 --> gss3.bdstatic.com:443 match DomainSuffix(bdstatic.com) using Domestic[DIRECT]"
2022-08-07 08:20:15 level=debug msg="[Process] find process gss3.bdstatic.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54374 --> ada.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:15 level=debug msg="[Process] find process ada.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54373 --> sp1.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:15 level=debug msg="[Process] find process sp1.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54372 --> sp1.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:15 level=debug msg="[Process] find process sp1.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:15 level=info msg="[TCP] 10.10.10.242:54371 --> nv00.cdn.bcebos.com:443 match IPCIDR(61.128.0.0/10) using Domestic[DIRECT]"
2022-08-07 08:20:15 level=debug msg="[Process] find process nv00.cdn.bcebos.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:13 level=info msg="[TCP] 10.10.10.242:54369 --> boxer.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:13 level=debug msg="[Process] find process boxer.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:13 level=info msg="[TCP] 10.10.10.242:54368 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:13 level=info msg="[TCP] 10.10.10.242:54367 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:13 level=info msg="[TCP] 10.10.10.242:54366 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:13 level=info msg="[TCP] 10.10.10.242:54365 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:13 level=info msg="[TCP] 10.10.10.242:54364 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:11 level=info msg="[TCP] 10.10.10.242:54363 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:11 level=info msg="[TCP] 10.10.10.242:54362 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:11 level=info msg="[TCP] 10.10.10.242:54361 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:08 level=info msg="[TCP] 10.10.10.242:54360 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:08 level=info msg="[TCP] 10.10.10.242:54359 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:08 level=info msg="[TCP] 10.10.10.242:54358 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54357 --> sv.bdstatic.com:443 match DomainSuffix(bdstatic.com) using Domestic[DIRECT]"
2022-08-07 08:20:07 level=debug msg="[Process] find process sv.bdstatic.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54356 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54355 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54354 --> hm.baidu.com:443 match Domain(hm.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54353 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54352 --> hm.baidu.com:443 match Domain(hm.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54351 --> hm.baidu.com:443 match Domain(hm.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54349 --> s.bdstatic.com:443 match DomainSuffix(bdstatic.com) using Domestic[DIRECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54350 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=debug msg="[Process] find process s.bdstatic.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54348 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54347 --> feed.baidu.com:443 match DomainSuffix(feed.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54346 --> m.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:07 level=debug msg="[Process] find process m.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54342 --> gimg1.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54345 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54341 --> ss0.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54339 --> ss0.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54340 --> ss0.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54344 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:06 level=debug msg="[Process] find process ss0.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:06 level=debug msg="[Process] find process ss0.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:06 level=debug msg="[Process] find process ss0.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:06 level=debug msg="[Process] find process gimg1.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54343 --> hpd.baidu.com:443 match DomainSuffix(hpd.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54338 --> hm.baidu.com:443 match Domain(hm.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54337 --> hm.baidu.com:443 match Domain(hm.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54336 --> hm.baidu.com:443 match Domain(hm.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54334 --> ocsp2.apple.com:443 match DomainSuffix(apple.com) using Apple[DIRECT]"
2022-08-07 08:20:06 level=debug msg="[Process] find process ocsp2.apple.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54329 --> hectorstatic.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54332 --> hm.baidu.com:443 match Domain(hm.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54331 --> hm.baidu.com:443 match Domain(hm.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:06 level=debug msg="[Process] find process hectorstatic.baidu.com: netlink message: NLMSG_ERROR"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54330 --> hm.baidu.com:443 match Domain(hm.baidu.com) using AdBlock[REJECT]"
2022-08-07 08:20:06 level=info msg="[TCP] 10.10.10.242:54328 --> www.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:06 level=debug msg="[Process] find process www.baidu.com: netlink message: NLMSG_ERROR"
```

### Description

路由器OpenClash TUN模式策略代理，手机通过AP访问m.baidu.com，一段时间后无法打开搜索结果的链接

这是手机浏览器的报错
![1](https://user-images.githubusercontent.com/63538901/183270356-90423fad-7acc-4e1b-822a-571aa1b90e4d.png)
![2](https://user-images.githubusercontent.com/63538901/183270359-3db66868-411b-4fe3-8815-02ac87a7c8ba.png)

这是要打开的链接
![3](https://user-images.githubusercontent.com/63538901/183270368-6972d343-5e4f-4a52-8b7e-936afff87d07.png)
![4](https://user-images.githubusercontent.com/63538901/183270370-1a1caf42-9930-49ee-9d4c-7ea349794f44.png)

这是相关的内核日志
2022-08-07 08:20:07 level=info msg="[TCP] 10.10.10.242:54346 --> m.baidu.com:443 match DomainSuffix(baidu.com) using Domestic[DIRECT]"
2022-08-07 08:20:07 level=debug msg="[Process] find process m.baidu.com: netlink message: NLMSG_ERROR"

**Comment by BirkhoffLee** [comment] 2022-08-27 03:59
duplicate of https://github.com/vernesong/OpenClash/issues/2307

**Closed by BirkhoffLee** 2022-08-27 03:59 UTC
Labels: help wanted
