### ISSUE TITLE
[Feature] SSH OUTBOUND

### ISSUE THREAD

**Issue by weihu120** [Dreamacro/clash#2609] opened 2023-03-14 02:10 UTC
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

会不会考虑增加ssh类型的outbound,就是sagernet和sing-box里的一样，这个很方便的啊，不需要专门安装服务端，能访问ssh server就能用，ssh被墙的几率也比其它翻墙协议低得多，虽然也可以手动ssh -D然后clash用socks并自动配置系统代理，但终归是麻烦一些。

**Comment by wenerme** [comment] 2023-03-29 09:51
xref https://github.com/Dreamacro/clash/issues/2183

**Comment by BirkhoffLee** [comment] 2023-04-28 12:51
Duplicate of #2183

**Closed by BirkhoffLee** 2023-04-28 12:51 UTC
