### ISSUE TITLE
[Feature] Use fingerprint detection resistant tls module

### ISSUE THREAD

**Issue by hiddify** [Dreamacro/clash#2344] opened 2022-10-13 08:59 UTC
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

Regarding to new reports https://github.com/net4people/bbs/issues/129 , GWF identify the tls connections made by golang.

### Possible Solution

Would you please use [this module](https://github.com/refraction-networking/utls) (undetectable tls) to avoid it?

**Comment by Dreamacro** [comment] 2022-10-13 09:04
Duplicate of #2339

**Closed by Dreamacro** 2022-10-13 09:04 UTC
