### ISSUE TITLE
[Feature] 支持vless

### ISSUE THREAD

**Issue by Hank-Chrome** [Dreamacro/clash#2528] opened 2023-02-06 06:06 UTC
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

能不能支持vless，支持了可以说是秒杀v2rayN

### Possible Solution

把xray-core代码搬过来就可以了吧

**Comment by Dreamacro** [comment] 2023-02-06 06:48
Duplicate of #1185

**Closed by Dreamacro** 2023-02-06 06:48 UTC
