### ISSUE TITLE
linux无可视化界面时，clash-ctl工具怎么使用？

### ISSUE THREAD

**Issue by zlsfe** [Dreamacro/clash#1713] opened 2021-11-03 02:50 UTC
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

linux无可视化界面时，clash-ctl工具怎么使用？
https://github.com/Dreamacro/clash-ctl

**Comment by Dreamacro** [comment] 2021-11-03 06:02
Duplicate of #1712

**Closed by Dreamacro** 2021-11-03 06:02 UTC
