### ISSUE TITLE
[Bug]Clash Premium  ARMv8 SSR节点无法打开网页

### ISSUE THREAD

**Issue by LSSCP** [Dreamacro/clash#1163] opened 2021-01-02 14:58 UTC
------------------------------------------------------------------

### Clash config

<details>
  <summary>config.yaml</summary>
mixed-port: 7890
allow-lan: true
mode: Rule
log-level: silent
external-ui: /home/clash/.config/clash/ui
Secret: 'xxxx'
external-controller: :9090
dns:
  enable: false
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  nameserver:
    - 119.29.29.29
    - 223.5.5.5

proxies:
  - {name: vmess, server: xxx, port: 443, type: vmess, xxx}
  - {name: trojan, server: xxx, port: 443, type: trojan,xxx}
  - {name: SS, server: xxx, port: 111, type: ss, cipher: rc4-md5, xxxxxx}
  - {name: SSR, server: jxxx, port: 111, type: ssr, cipher: rc4-md5, xxxxx}
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - vmess
      - torjan
      - SSR
      - SS
rule-providers:
  Proxy:
    type: file
    behavior: classical
    path: ./rule-set/Proxy.list

rules:
 - RULE-SET,Proxy,Proxy
 - MATCH,DIRECT
```yaml
……
```

</details>

### Clash log

```
Jan  2 22:29:39 ubuntu clash-linux-armv8-2020.12.27[6444]: time="2021-01-02T22:29:39+08:00" level=info msg="[TCP] 192.168.2.9:63647 --> www.google.com match RuleSet(Proxy) using Proxy[SSR]"
Jan  2 22:29:52 ubuntu clash-linux-armv8-2020.12.27[6444]: time="2021-01-02T22:29:52+08:00" level=debug msg="[Rule] find process name Process error: no such process"
Jan  2 22:29:52 ubuntu clash-linux-armv8-2020.12.27[6444]: time="2021-01-02T22:29:52+08:00" level=debug msg="[DNS] clients1.google.com --> 172.217.160.110"
Jan  2 22:29:52 ubuntu clash-linux-armv8-2020.12.27[6444]: time="2021-01-02T22:29:52+08:00" level=info msg="[TCP] 192.168.2.9:63648 --> clients1.google.com match RuleSet(Proxy) using Proxy[SSR]"
```

### 环境 Environment

* 操作系统 (the OS that the Clash core is running on)
ubuntu
……
* 网路环境或拓扑 (network conditions/topology)
pc(192.168.2.5)-树莓派clash(192.168.2.3)-router(192.168.2.1)-公网
……
* iptables，如果适用 (if applicable)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他 (any other information that would be useful)
……

### 说明 Description

通过socks或者http的方式设置系统代理连接树莓派上的clash,然后通过SSR节点访问网站失败,但是ss,trojan,vmess协议能够正常访问.
SSR节点在pc版 clash上可以正常使用.
用tunnel方式使用clash,ssr节点也能正常使用.

### 重现问题的具体布骤 Steps to Reproduce

1. 我这里只要socks或者http接受传入,SSR协议传出就能重现问题.

**我预期会发生……？**

正常打开网页
**实际上发生了什么？**

网页载入失败,但是log里看着像是正常发起连接,也没有报错.

**Comment by ElectronicElephant** [comment] 2021-01-22 08:20
可能与 #995 重复了

**Comment by Dreamacro** [comment] 2021-02-15 06:34
Duplicate of #995

**Closed by Dreamacro** 2021-02-15 06:34 UTC
