### ISSUE TITLE
[Feature] vless这么主流的协议，clash怎么能不支持呢!望大大尽快更新…

### ISSUE THREAD

**Issue by linglala** [Dreamacro/clash#2271] opened 2022-08-21 15:58 UTC
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

 vless这么主流的协议，clash怎么能不支持呢!望大大尽快更新…

**Comment by Dreamacro** [comment] 2022-08-22 01:52
Duplicate of #1185

**Closed by Dreamacro** 2022-08-22 01:52 UTC
